import type { SecurityCheck } from '../../types';

/**
 * 安全检查测试数据
 */
export const testData: SecurityCheck[] = [
  {
    samplingId: 'SC001',
    reportId: 'RPT001',
    userId: 'U001',
    name: '张三',
    deviceId: 'DEV001',
    updateDate: '2024-01-15',
    updateTime: '2024-01-15 10:30:00',
    createTime: '2024-01-10 09:00:00',
    updater: 'admin',
    creater: 'admin',
    bootAuthentication: true,
    screenSaverPwd: true,
    installedSoftware: true,
    securityPatch: true,
    antivirusProtection: true,
    usbInterface: false,
    disposalMeasures: 'USB接口已禁用',
  },
  {
    samplingId: 'SC002',
    reportId: 'RPT002',
    userId: 'U002',
    name: '李四',
    deviceId: 'DEV002',
    updateDate: '2024-01-16',
    updateTime: '2024-01-16 14:20:00',
    createTime: '2024-01-11 10:00:00',
    updater: 'admin',
    creater: 'admin',
    bootAuthentication: true,
    screenSaverPwd: false,
    installedSoftware: true,
    securityPatch: true,
    antivirusProtection: true,
    usbInterface: true,
    disposalMeasures: '已要求用户设置屏保密码',
  },
  {
    samplingId: 'SC003',
    reportId: 'RPT003',
    userId: 'U003',
    name: '王五',
    deviceId: 'DEV003',
    updateDate: '2024-01-17',
    updateTime: '2024-01-17 16:45:00',
    createTime: '2024-01-12 11:00:00',
    updater: 'admin',
    creater: 'admin',
    bootAuthentication: false,
    screenSaverPwd: true,
    installedSoftware: false,
    securityPatch: false,
    antivirusProtection: true,
    usbInterface: true,
    disposalMeasures: '发现未授权软件，已卸载；安全补丁待更新',
  },
  {
    samplingId: 'SC004',
    reportId: 'RPT004',
    userId: 'U004',
    name: '赵六',
    deviceId: 'DEV004',
    updateDate: '2024-01-18',
    updateTime: '2024-01-18 09:15:00',
    createTime: '2024-01-13 08:30:00',
    updater: 'admin',
    creater: 'admin',
    bootAuthentication: true,
    screenSaverPwd: true,
    installedSoftware: true,
    securityPatch: true,
    antivirusProtection: false,
    usbInterface: true,
    disposalMeasures: '杀毒软件未运行，已重新启动',
  },
  {
    samplingId: 'SC005',
    reportId: 'RPT005',
    userId: 'U005',
    name: '孙七',
    deviceId: 'DEV005',
    updateDate: '2024-01-19',
    updateTime: '2024-01-19 11:30:00',
    createTime: '2024-01-14 09:45:00',
    updater: 'admin',
    creater: 'admin',
    bootAuthentication: true,
    screenSaverPwd: true,
    installedSoftware: true,
    securityPatch: true,
    antivirusProtection: true,
    usbInterface: true,
    disposalMeasures: '',
  },
  {
    samplingId: 'SC006',
    reportId: 'RPT006',
    userId: 'U006',
    name: '周八',
    deviceId: 'DEV006',
    updateDate: '2024-01-20',
    updateTime: '2024-01-20 13:00:00',
    createTime: '2024-01-15 10:00:00',
    updater: 'admin',
    creater: 'admin',
    bootAuthentication: false,
    screenSaverPwd: false,
    installedSoftware: false,
    securityPatch: false,
    antivirusProtection: false,
    usbInterface: false,
    disposalMeasures: '设备存在多项安全隐患，已暂停使用并进行全面整改',
  },
  {
    samplingId: 'SC007',
    reportId: 'RPT007',
    userId: 'U007',
    name: '吴九',
    deviceId: 'DEV007',
    updateDate: '2024-01-21',
    updateTime: '2024-01-21 15:30:00',
    createTime: '2024-01-16 11:00:00',
    updater: 'admin',
    creater: 'admin',
    bootAuthentication: true,
    screenSaverPwd: true,
    installedSoftware: false,
    securityPatch: true,
    antivirusProtection: true,
    usbInterface: true,
    disposalMeasures: '发现游戏软件，已删除并警告',
  },
  {
    samplingId: 'SC008',
    reportId: 'RPT008',
    userId: 'U008',
    name: '郑十',
    deviceId: 'DEV008',
    updateDate: '2024-01-22',
    updateTime: '2024-01-22 10:00:00',
    createTime: '2024-01-17 09:00:00',
    updater: 'admin',
    creater: 'admin',
    bootAuthentication: true,
    screenSaverPwd: true,
    installedSoftware: true,
    securityPatch: false,
    antivirusProtection: true,
    usbInterface: true,
    disposalMeasures: '系统补丁更新中',
  },
  {
    samplingId: 'SC009',
    reportId: 'RPT009',
    userId: 'U009',
    name: '钱十一',
    deviceId: 'DEV009',
    updateDate: '2024-01-23',
    updateTime: '2024-01-23 14:45:00',
    createTime: '2024-01-18 10:30:00',
    updater: 'admin',
    creater: 'admin',
    bootAuthentication: true,
    screenSaverPwd: true,
    installedSoftware: true,
    securityPatch: true,
    antivirusProtection: true,
    usbInterface: true,
    disposalMeasures: '',
  },
  {
    samplingId: 'SC010',
    reportId: 'RPT010',
    userId: 'U010',
    name: '孙十二',
    deviceId: 'DEV010',
    updateDate: '2024-01-24',
    updateTime: '2024-01-24 16:20:00',
    createTime: '2024-01-19 11:00:00',
    updater: 'admin',
    creater: 'admin',
    bootAuthentication: true,
    screenSaverPwd: false,
    installedSoftware: true,
    securityPatch: true,
    antivirusProtection: false,
    usbInterface: true,
    disposalMeasures: '屏保密码未设置，杀毒软件已过期，正在处理',
  },
];
